apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironmind-backend
  namespace: ironmind
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ironmind-backend
  template:
    metadata:
      labels:
        app: ironmind-backend
    spec:
      containers:
      - name: backend
        image: ironmind/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: ironmind-config
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ironmind-secrets
              key: openai-api-key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ironmind-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ironmind-secrets
              key: aws-secret-access-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5 