apiVersion: v1
kind: Secret
metadata:
  name: ironmind-secrets
  namespace: ironmind
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  openai-api-key: <base64-encoded-openai-key>
  aws-access-key-id: <base64-encoded-aws-access-key>
  aws-secret-access-key: <base64-encoded-aws-secret-key>
  postgres-password: aXJvbm1pbmQ= # ironmind in base64 